### ISSUE TITLE
opensky sensor not working

### ISSUE THREAD

**Issue by yousaf465** [joostlek/python-opensky#49]
# Problem/Motivation

OpenSky sensor not being created

## Expected behavior

Opensky sensors to show up in HA

## Actual behavior

no sensors in dev>states
logs
```Logger: homeassistant.components.sensor
Source: components/opensky/sensor.py:163
Integration: Sensor (documentation, issues)
First occurred: 8:57:23 AM (1 occurrences)
Last logged: 8:57:23 AM

opensky: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 537, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/opensky/sensor.py", line 163, in async_update
    response = await self._opensky.get_states(bounding_box=self._bounding_box)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/python_opensky/opensky.py", line 148, in get_states
    "states": [self._convert_state(state) for state in data["states"]],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by joostlek** [comment]
By the way, what HA version are you on?

**Comment by yousaf465** [comment]
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by joostlek** [comment]
Apparently when OpenSky could not find any states, it returned no list instead of an empty list. Fixed it, made PR for HA to fix this aswell.
